BakeryShop/Models/ShopViewModel.cs
using X.PagedList;

namespace BakeryShop.Models
{
    public class ShopViewModel
    {
        public IPagedList<ProductViewModel>? PagedProducts { get; set; }
        public List<CategoryViewModel>? Categories { get; set; }
    }
}

BakeryShop/Controllers/DetailController.cs
using AutoMapper;
using BakeryShop.Models;
using Infrastructure.Entities;
using Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace BakeryShop.Controllers
{
    public class DetailController : Controller
    {
        private readonly IProductsService _productsService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;

        public DetailController(IProductsService productsService, ICategoryService categoryService, IMapper mapper)
        {
            _productsService = productsService;
            _categoryService = categoryService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int id)
        {
            
            Product product = await _productsService.GetProduct(id);

            if (product != null)
            {
             
                ProductViewModel productViewModel = _mapper.Map<ProductViewModel>(product);
                return View(productViewModel);
            }
            else
            {
                return NotFound(); 
            }
            
        }

    }
}

BakeryShop/Controllers/ShopController.cs
using AutoMapper;
using BakeryShop.Models;
using Infrastructure.Entities;
using Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using X.PagedList;

namespace BakeryShop.Controllers
{
    public class ShopController : Controller
    {
        private readonly ILogger<ShopController> _logger;
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;
        private readonly IProductsService _productsService;
        public ShopController(ILogger<ShopController> logger, IMapper mapper, ICategoryService categoryService, IProductsService productsService)
        {
            _logger = logger;
            _mapper = mapper;
            _categoryService = categoryService;
            _productsService = productsService;
        }
        public async Task<IActionResult> Index(int? page, string searchString, int category, int maxPrice,int minPrice)
        {
            try
            {
                int pageSize = 4;
                int pageNumber = (page ?? 1);
               

                IQueryable<Product> listProduct = await _productsService.GetProducts();
                if (!String.IsNullOrEmpty(searchString))
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true && e.ProductName.Contains(searchString)).Select(e => e);
                }
                else
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true).Select(e => e);
                }
                if (category!=0)
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true && e.CategoryId==category).Select(e => e);
                }
                else
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true).Select(e => e);
                }
                if (maxPrice != 0)
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true && e.Price>=minPrice && e.Price<=maxPrice).Select(e => e);
                }
                else
                {
                    listProduct = listProduct.Where(e => e.IsUsed == true).Select(e => e);
                }

                List<ProductViewModel> products = _mapper.Map<List<ProductViewModel>>(listProduct.ToList());
                IQueryable<Category> categories = await _categoryService.GetCategories();
                List<CategoryViewModel> categoriesModel = _mapper.Map<List<CategoryViewModel>>(categories.ToList());

                foreach (ProductViewModel product in products)
                {
                    product.Category = categories.FirstOrDefault(c => c.CategoryId == product.CategoryId);
                }
                
                ShopViewModel viewModel = new ShopViewModel
                {
                    PagedProducts = await products.ToPagedListAsync(pageNumber, pageSize),
                    Categories = categoriesModel
                };

                return View("Index", viewModel);
                
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

        }
    }
}

BakeryShop/Views/Shop/Index.cshtml
@using Infrastructure.Entities;
@using Newtonsoft.Json;
@using X.PagedList.Mvc
@using X.PagedList
@using X.PagedList.Web.Common
@using X.PagedList.Mvc.Core
@model ShopViewModel

<!DOCTYPE html>
<html lang="en">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<body>

    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>
        <div class="shop_sidebar_area">
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Danh mục</h6>
               
                <!--  Catagories  -->
                <div class="catagories-menu">
                    <ul>

                        @foreach (CategoryViewModel categoryViewModel in Model.Categories)
                        {
                            //href="@Url.Action("Index", "Detail", new { id = product.ProductID })
                            <li><a href="@Url.Action("Index", "Shop", new { category = categoryViewModel.CategoryID })">@categoryViewModel.CategoryName</a></li>
                        }
                    </ul>
                </div>
            </div>
            <div class="widget price mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Gía</h6>

                <div class="widget-desc">
                    <div class="slider-range">
                        <div data-min="0" data-max="1000000" data-unit="" class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" data-value-min="0" data-value-max="1000000" data-label-result="">
                            <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                            <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                        </div>
                        <div class="range-price">0 - 1000000</div>
                        <a id="filter-link" href="#" class="btn amado-btn active">Lọc sản phẩm</a>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                $(".slider-range-price").slider({
                    range: true,
                    min: 0,
                    max: 1000000,
                    values: [0, 1000000],
                    slide: function (event, ui) {
                        $(".range-price").text(ui.values[0] + " - " + ui.values[1]);
                    }
                });

                $("#filter-link").click(function (e) {
                    e.preventDefault();
                    var minPrice = $(".slider-range-price").slider("values", 0);
                    var maxPrice = $(".slider-range-price").slider("values", 1);
                    var url = "/Shop/Index?minPrice=" + minPrice + "&maxPrice=" + maxPrice;
                    window.location.href = url;
                });
            });
        </script>

      
        <div class="amado_product_area section-padding-100">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <h6 class="widget-title mb-30">Lọc sản phẩm theo nhiều yếu tố</h6>
                        <div class="product-topbar d-xl-flex align-items-end justify-content-between">
                         
                            <!-- Sorting -->
                            <div class="product-sorting d-flex">
                                <div class="sort-by-date d-flex align-items-center mr-15">

                                    <form action="@Url.Action("Index", "Shop")" method="get" class="form-inline">
                                        <div class="form-group">
                                            <input type="text" name="searchString" class="form-control" placeholder="Tìm kiếm...">
                                        </div>

                                        <div class="form-group">
                                            <select name="category" class="form-control">
                                                <option value="">Chọn danh mục</option>
                                                @foreach (CategoryViewModel categoryViewModel in Model.Categories)
                                                {
                                                    <option value="@categoryViewModel.CategoryID">@categoryViewModel.CategoryName</option>
                                                }
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <input type="number" name="minPrice" class="form-control" placeholder="Giá tối thiểu">
                                        </div>

                                        <div class="form-group">
                                            <input type="number" name="maxPrice" class="form-control" placeholder="Giá tối đa">
                                        </div>

                                        <button type="submit" class="btn amado-btn active">Lọc sản phẩm</button>
                                    </form>
                                </div>
                             
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                     <!-- Single Catagory -->
          @foreach (ProductViewModel product in Model.PagedProducts)
        {
                        if (product.IsUsed == true)
                        {
                            <!-- Single Product Area -->
                            <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                                <div class="single-product-wrapper">
                                    <!-- Product Image -->
                                    <div class="product-img" >
                                        <img style="height:400px;" src="data:image;base64,@Convert.ToBase64String(product.Image)" alt="">
                                        <!-- Hover Thumb -->
                                        
                                    </div>

                                    <!-- Product Description -->
                                    <div class="product-description d-flex align-items-center justify-content-between">
                                        <!-- Product Meta Data -->
                                        <div class="product-meta-data">
                                            <div class="line"></div>
                                            <p class="product-price">@product.Price</p>
                                            <!-- ở đây -->
                                            <a href="@Url.Action("Index", "Detail", new { id = product.ProductID  })"    >
                                                <h6>@product.ProductName</h6>
                                            </a>
                                        </div>
                                        <!-- Ratings & Cart -->
                                        <div class="ratings-cart text-right">
                                            <div class="ratings">
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                            </div>
                                            <div class="cart">
                                                <a href="cart.html" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="img/core-img/cart.png" alt=""></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
        }

                </div>

                <div class="row">
                    <div class="col-12">
                        <!-- Pagination -->
                        <nav aria-label="navigation">
                            <ul class="pagination justify-content-end mt-50">
                                @if (Model.PagedProducts.HasPreviousPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = 1 })">First</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PagedProducts.PageNumber - 1 })">Pre</a>
                                    </li>
                                }

                                @for (int i = 1; i <= Model.PagedProducts.PageCount; i++)
                                {
                                    <li class="page-item @(i == Model.PagedProducts.PageNumber ? "active" : "")">
                                        <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                                    </li>
                                }

                                @if (Model.PagedProducts.HasNextPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PagedProducts.PageNumber + 1 })">Next</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PagedProducts.PageCount })">Last</a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

</body>

</html>